### ISSUE TITLE
HC-Web: Adding hasher to mismanagement disappears the options

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#100]
After giving myself Mismanagement permissions in HC-Web for "Puget Sound H3" and "Rain City H3", the links disappear, even after a browser refresh. Also, the "IsMember" flag cannot be changed from this interface...is there a way to change that in the app? Neither of these kennels has had an actual event in Harrier Central yet.

![2021-09-14 10_27_54-Hasher List - HcWeb](https://user-images.githubusercontent.com/49632769/133305902-68fd643b-49e3-4ef3-b5c4-2e462112cba0.jpg)

![2021-09-14 10_32_24-Hasher List - HcWeb](https://user-images.githubusercontent.com/49632769/133306160-8275c4fc-1e56-49a0-8645-3fe61346d7b7.jpg)

**Comment by James-A-White** [comment]
The new portal should allow you to do this.  We will be replacing the old portal (currently admin.harriercentral.com) with the new one (portal.harriercentral.com).

Are you able to do what you need with the new portal? If so, I'll close this issue.

**Comment by diabWH3** [comment]
I believe this issue was related to #182 and has been resolved for the "old" portal. 

I actually don't see any way to edit Mismanagement permissions/roles in the new portal.

**Comment by James-A-White** [comment]
Hey DIAB, you can use the app to assign Mismanagement roles and permissions. It is not yet on the new portal. I'm going to leave this open to track that feature enhancement to the new portal.

**Comment by diabWH3** [comment]
That's great! After sending that last note, I found the HC Admin controls,
but had overlooked the Mismanagement controls. Thanks for pointing that out
and adding it to the app to help keep everything mostly in a single spot. :)

**Comment by James-A-White** [comment]
Closing as the app has an option to do this. Will eventually add to the new HC portal
