### ISSUE TITLE
HC-Web/Google Sheets: Only adds 6 new names at a time

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#101]
Testing the bulk "add new members" feature via Google Sheets for the Puget Sound H3 kennel. The integration with Azure worked for the first 6 entries, but then timed out with the following error. It then would not work for any further entries, even if I started with a new, smaller, batch of names.
![2021-09-14 11_34_42-hcazurefunctions7 azurewebsites net](https://user-images.githubusercontent.com/49632769/133314959-a788b62d-516a-4e14-b66d-d95a87a5e795.jpg)

**Comment by James-A-White** [comment]
We have decided not to continue with Google sheets as a way to interface with the back end DB. Will close this and all other Google Sheets related issues.
