### ISSUE TITLE
HC-Web/Google Sheets: New members added display as Mortal Name

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#102]
After using the batch 'add new members' feature of Google Sheets, the newly-added members show in the HC-Web interface as their Mortal Names. You can click on each name, update the settings, and refresh the membership list and it will properly show Hash Names instead.

![2021-09-14 11_40_26-Hasher List - HcWeb](https://user-images.githubusercontent.com/49632769/133315441-1222145a-03b1-4d24-ba8a-02466f603ddc.jpg)

**Comment by James-A-White** [comment]
We have decided not to continue with Google sheets as a way to interface with the back end DB. Will close this and all other Google Sheets related issues.
