### ISSUE TITLE
HC-Mobile: Hash Cash credit not calculating properly

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#135]
Last night was the 2nd run trying to build credit for hasher overpayments (i.e. paying $20 to build credit for future runs).
We encountered multiple issues with the app not calculating credit appropriately.
Test data can be seen for SeaMon H3 trails #314 and #315 and for hashers: My Little Penis, Shackless!!!, and Cougar Rican.

All cases: trail cost is $5

1. **Cougar Rican**
- Paid $10 at trail #309 to establish a surplus credit of $5
- App and Hash Cash Report both correctly show $5 credit

2. **My Little Penis**
- Paid $20 at trail #314, but the Hash Cash Report calculates the remaining credit as $10 instead of $15
- Successfully redeemed $5 of the $10 credit at trail #315, leaving $5 in credit remaining (should actually be $10)

3. **Shackless**
- Paid $20 at trail #314, establishing $15 credit. The Hash Cash Report correctly calculates this.
- As of trail #315, the app does not recognize him as having any credit balance, despite the Hash Cash Report still being accurate.

**Comment by James-A-White** [comment]
OK....  making a bit of progress here.  For Shackless, he was not a member. Currently, we only allow Kennel members to pay with credit.

Here's what the screen looks like when he is not a member:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/5836474/137176400-6322044e-644c-44e3-bc50-67629a85a6b9.png">


... and here's what it looks like when you make him a member.  Note the addition of the "pay with credit" button.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/5836474/137176104-7f8b7413-e89d-4cf9-a5f4-a0369256811e.png">

Does this address the issue with Shackless?

I'll look into My Little Penis next.

**Comment by James-A-White** [comment]
It looks like the credit remaining for My Little Penis is correct. Apparently on Run #313, Cougar Rican selected "pay by credit" which gave My Little Penis a -$5.00 balance. When she then paid for the next run with $20, it subtracted $5 for the run and applied $5 to the outstanding balance from run 313, leaving $10 of credit remaining. So, the question is, did My Little Penis pay cash for run 313 and did Cougar Rican push the wrong button on the app?  I'll leave this open for now until we have confirmed that the app is indeed working correctly.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/5836474/137215517-4aeb1c45-80bf-4263-90e8-b8edee02977c.png">

**Comment by James-A-White** [comment]
By the way... to make someone a member, follow these steps:


<img width="444" alt="image" src="https://user-images.githubusercontent.com/5836474/137216440-4b53047a-7b45-4b07-9ac9-00092d965544.png">


<img width="431" alt="image" src="https://user-images.githubusercontent.com/5836474/137216352-a6c1378e-3116-4bd0-a2f5-3748bf94a660.png">

<img width="441" alt="image" src="https://user-images.githubusercontent.com/5836474/137216561-da936f12-7c1c-444a-b2cb-55bba210e0db.png">

The same steps can be used to terminate someone's membership.

**Comment by diabWH3** [comment]
Super awesome info, thank you!

The home vs member status makes a ton of sense and I think the current
behavior is ideal.
I completely forgot about the "Manage Members" portion of the app; I will
ensure Shackless is a member and that I update his credit usage
appropriately.
As for MLP, it appears as though the system is working correctly and I'll
have to figure out if she actually paid for trail #313 or not (the one
where she established negative credit).

Thanks for doing some digging on this one! I think that resolves my issues
and, moving forward, I think an enhancement could be to somehow prevent or
warn when a non-member wants to over/under pay.

>
