### ISSUE TITLE
Implement auto check-in

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#15]
Auto detect when someone is close to a run start and time and prompt them to check in at the Hash

**Comment by James-A-White** [comment]
Implemented in 0.8.142+297. 

A check-in prompt will appear for users when they open an app +/- 4 hours from the start of a run and when they are within 1500 meters of the designated start point.

Seems to work reliably, but needs testing.

**Comment by modderkabouter** [comment]
what if a hasher lives less than 1500m from the start point but is not cumming for whatever reason?
