### ISSUE TITLE
User Info: Unable to edit Hash Cash from some past events -> causing user credit issues

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#168]
Have a hasher that hasn't attended a SeaMon H3 event since early 2020 and has some "fake" credit that we used on test events while originally testing the app with our kennel. The user doesn't actually have any credit established with us and I can't seem to find the events in the app in order to go back and cancel or edit the transactions that created this credit amount.
The attached image is a chronological list of all transactions for hasher "JK LOL". None of the "Cash +" entries are correct due to testing.

![2021-11-07 23_23_51-Ad Hash Cash Report - HcWeb](https://user-images.githubusercontent.com/49632769/140700811-1bcb7489-3e32-4eca-bab9-9896b01b7798.jpg)

**Comment by James-A-White** [comment]
Hey DIAB, thanks for reporting this. I will look into the issue and see why you are unable to cancel those transactions. I've been laser focused on finishing the Website "plug-in" that will allow Kennels to display information from our system directly on their Hash web pages. It's nearly done, but has been consuming a lot of my time, which is why I'm behind on bug fixes. Hopefully all of your issues will be resolved soon!

**Comment by James-A-White** [comment]
Hey DIAB. This can be handled through the app. I'll post screenshots below with steps... Give this a try and let me know if you get it to work.  I'm going to close this issue, but feel free to reopen it if you have a problem.


<img width="368" alt="image" src="https://user-images.githubusercontent.com/5836474/142938682-2bc53e84-4eae-4b92-8292-58ee445bfbaa.png">

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5836474/142938784-4b01524b-f86d-4e98-a85b-64d90e8718bd.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/5836474/142938924-b84e10dd-619c-4bd0-bb27-3517cd4e3499.png">

<img width="369" alt="image" src="https://user-images.githubusercontent.com/5836474/142939061-49b646bd-c3e5-4947-b086-dc52e896c518.png">

**Comment by diabWH3** [comment]
Thanks! I forgot about that functionality in the app. I've canceled that
problematic transaction.
