### ISSUE TITLE
HC-App, Enhancement: Add "True North" map button

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#181]
Add a button to re-orient all map views (multiple locations throughout the app) to a north = up view. It's very sensitive to multi-touch rotations, so is easy to misorient without having an easy way to undo that.

**Comment by James-A-White** [comment]
Good comment...  should I have a setting in the app that allows you to lock the maps to true north?

**Comment by diabWH3** [comment]
Maybe the icon can have two functions: if the map is rotated, pressing once
will re-orient the map to true north, but if it's already on true north,
pressing the icon will lock it to true north. If it's locked, pressing it
again will unlock and allow for rotation via multi-point gesture.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*

**Comment by James-A-White** [comment]
Implemented in HC version 1.0.35 on the main map view and the map view used to edit run details. Click for "true north" and it reorients and map and locks it to N, click again and the map can be rotated. Thanks DIAB! Good feedback!
