### ISSUE TITLE
HC-Web, Bug: Mismanagement controls disappeared from Admin web portal

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#182]
Not exactly sure what I did, but my controls to see and change Mismanagement members disappeared from the "Hashers" screen on the HC-Web admin portal. I was updating my roles within SeaMon H3 and I think I checked the "GM" box and saved my changes. After that, I was no longer able to see or change anyone's mismanagement status.

I must still have admin controls because I can still edit kennel, trail, and hasher details from the app and the web portal.

![2021-11-16 21_26_02-Hasher List - HcWeb](https://user-images.githubusercontent.com/49632769/142140490-d450bfb8-f890-41a8-80f8-f566742e8cc7.jpg)

**Comment by James-A-White** [comment]
Oops! Will look at this tonight!

**Comment by James-A-White** [comment]
Hey DIAB, Can you log in and try again?  There were a few permissions that needed to be enabled and you should have full permissions now. I'll leave this open until I get confirmation that it's working for you.  Sorry again for the delay in getting this resolved. Been quite busy!

OnOn!

Opee

**Comment by diabWH3** [comment]
Confirmed this is working again. Thanks!
Issue can be closed.

**Comment by James-A-White** [comment]
Cool... glad it's fixed!
