### ISSUE TITLE
Bug: Location information not interpreted the same between HC-Web and HC-App

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#185]
This is for Puget Sound H3 run #1101.
Created and updated the event info in HC-Web, including only a residential street address (hare's house). The "Test location in web browser" button works correctly. 
![2021-11-18 09_27_30-Calculator](https://user-images.githubusercontent.com/49632769/142466322-09f8e0b6-b9d9-492c-9079-b4fa61e1658a.jpg)
However, when viewing the "Map" page in HC-App, it shows as "No location provided".
![Screenshot_20211118-092634](https://user-images.githubusercontent.com/49632769/142466532-9ba875be-9b98-4ce7-b47b-6c866fc17511.png)

**Comment by James-A-White** [comment]
Thanks for this...   We are re-architecting how the portal works and replacing it with a new portal. For the near term if you can use the HC App to set the location that would be a good workaround. Once the new portal is out, you will be able to set run locations on the Web. We are no longer actively updating features on the "old" portal (the one located at admin.harriercentral.com) and will be building them into the new portal, located at https://portal.harriercentral.com/

In the near term, please use the app to set the location. Go to the admin screen for the run and set the location there.

We hope to have an add/edit run capability soon on the new HC portal.  I'm going to close this for now, but please feel free to reopen it if you are either unable to use the app to set run locations or if we do not implement this in the new portal shortly.
