### ISSUE TITLE
BUG: Unable to add new user from trail admin page

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#193]
While taking manual attendance at trail last night, I needed to add a new hasher through the app. The new hasher entry page no longer requests an email address, which is nice, but does not seem to save properly. After pressing the "Add Hasher" button, the user is taken to a screen displaying "Loading / Updating User Profile" and the spinning wheel of death. After a while, it times out and gives an error message relating to a connectivity timeout. 
![Screenshot_20211130-083322](https://user-images.githubusercontent.com/49632769/144089099-23aad057-415b-46f5-979d-cb3a725eeacf.png)
![Screenshot_20211130-083330](https://user-images.githubusercontent.com/49632769/144089103-85fab722-1a5a-46a2-a36c-ade4ebaefb38.png)
![Screenshot_20211130-083424](https://user-images.githubusercontent.com/49632769/144089105-3a9e801e-8aea-4f70-9818-210997d09d12.png)

**Comment by James-A-White** [comment]
Fixed in 1.0.40.  Will open new issue to fix this dialog...

<img width="435" alt="image" src="https://user-images.githubusercontent.com/5836474/144175291-fc58b44e-5878-4841-9f74-17a0b2c6835a.png">
