### ISSUE TITLE
BUG, HC-App: Grey screen when navigating "out" of a past trail's admin screen

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#195]
On a past trail, the user gets a blank grey screen instead of the trail info page when navigating "back" from the trail's admin page.

Using latest Android version.
To reproduce: go to a past trail, enter the admin screen, press the OS "back" button.

![Screenshot_20211130-090113](https://user-images.githubusercontent.com/49632769/144093370-8d610fc9-ec0f-459d-901d-3251d2ac670d.png)

**Comment by James-A-White** [comment]
I am unable to reliably reproduce this. It may be related to a specific run. Can you indicate which runs this happens with so I can try to replicate? Thanks!

**Comment by diabWH3** [comment]
This happens for every single past SeaMon H3 trail. 
This happens when in the admin screen and pressing either the OS or on-screen "back" buttons.

**Comment by diabWH3** [comment]
![Screenshot_20211228-091348](https://user-images.githubusercontent.com/49632769/147590686-411d487f-ec93-474c-9c8b-f34aad93cc53.png)

**Comment by James-A-White** [comment]
I wonder if this is a device-based issue... my Android phone works OK. I'll tinker with it some more tonight. Thanks for the update and sorry for the issue!

**Comment by James-A-White** [comment]
Fixed in 1.0.65.
