### ISSUE TITLE
Enhancement, HC-App: User's history page shows all kennels, despite "following" status or "0" run counts

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#196]
Think of some way to limit the number of kennels showing on this page. Maybe only kennels that are being "followed" and/or have a "greater than zero" run count.

![Screenshot_20211130-090436](https://user-images.githubusercontent.com/49632769/144093771-281ca3a1-797a-4ab5-91a9-3954d6f483dd.png)

**Comment by James-A-White** [comment]
Good catch DIAB. This was a regression that resulted from my complete re-working of the run count infrastructure on both the backend and the app. 

Fixed in 1.0.40.

If the next version does not meet your expectations for functionality, please reopen this issue.
