### ISSUE TITLE
Fix this crappy looking dialog

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#199]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/5836474/144175330-f9b8c9a5-9949-459e-8748-c3bfc0063103.png">

**Comment by diabWH3** [comment]
LOL! I love this ticket! :)

**Comment by James-A-White** [comment]
Fixed in 1.0.40

<img width="413" alt="image" src="https://user-images.githubusercontent.com/5836474/144422537-f4460638-cdf9-47c8-b31e-2a78343dfa62.png">
