### ISSUE TITLE
Swiping between pages

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#20]
Hey, first thing Pink tried when opening the app was swiping right and left to go between the pages.  Think it might be a good idea.

Sugar Tits

**Comment by James-A-White** [comment]
I'll have to think about this. The problem is that the map view uses swipes to move the map, so you could swipe to get to it, but not swipe to move away from it. I'm not sure that would be the best user experience.

**Comment by modderkabouter** [comment]
ok good point

Op do 26 mrt. 2020 om 22:47 schreef James-A-White <notifications@github.com

**Comment by James-A-White** [comment]
Cannot think of a better way to implement this given the current UI. Going to close for now, but still interested to see if there is a solution.
