### ISSUE TITLE
BUG, HC-App: Kennel Info page does not show all Mismanagement roles

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#201]
Related to the comment below and referencing Rain City H3:
The Kennel Info page doesn't seem to update to show app-assigned Mismanagement roles:
- Mexican Rimjob as GM
- Cosmo as Religious Advisor

*******
Hey DIAB, you can use the app to assign Mismanagement roles and permissions. It is not yet on the new portal. I'm going to leave this open to track that feature enhancement to the new portal.

_Originally posted by @James-A-White in https://github.com/James-A-White/HarrierCentral/issues/100#issuecomment-985013946_

**Comment by diabWH3** [comment]
![Uploading Screenshot_20211202-163017.png…]()

**Comment by James-A-White** [comment]
Fixed in 1.0.55. The data was being properly handled but the screen was not refreshing properly when popped back to from the Members view.
