### ISSUE TITLE
BUG, HC-App: Unable to send trail detail emails

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#205]
Error message while trying to send out trail details for tonight's (Dec. 6th) SeaMon H3 trail, using the app.
Maybe related to #170 ?

![Screenshot_20211206-105347](https://user-images.githubusercontent.com/49632769/144945326-52adfc64-0c0a-4c55-99cf-72446af04161.png)

**Comment by James-A-White** [comment]
I think this may have been related to the fact that the server was temporarily down as I was implementing San Diego Kennel integration. I think I've received an email from you since then. Please close this if you see that it is working again.

**Comment by diabWH3** [comment]
Correct, it seems to work now!

---
Joshua Johnson
352.538.7567
