### ISSUE TITLE
HC-App - Enhancement: Add "use your credit" button to trail payment screen for applicable users

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#212]
Similar to how the PayPal payment button appears within 24 hours of trail start time, if a user has kennel credit (either >0.00 or >= trail cost), a button should show allowing them to choose to use their existing credit to pay for trail.

If their credit is less than trail cost, there would have to be some notification showing them they still owe a balance, so maybe it's best to only show that button if the user has sufficient credit for that run.

This would be good because there's no existing way for users to check their own credit balances.

**Comment by James-A-White** [comment]
Done and pushed to the App Store. Please test and let me know how it works. Great suggestion!

**Comment by diabWH3** [comment]
None of the users with existing credit could see the notification at trail last night. Did not confirm if their app was updated to latest version or not.
