### ISSUE TITLE
Random city: Ottawa, Canada is apparently in Erie, New York

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#219]
Rideau H3: When we have a very definite place, and Facebook even is showing
an arrow, we get weird stuff like the attached where it says:
   Region: Erie
   State: New York
   Country: Canada

Maybe this error is coming from Facebook, if so I can't tell myself.

**Comment by mcr** [comment]
DumbleDick is also @mcr :-)

**Comment by James-A-White** [comment]
I think this was bad data coming from Facebook. If we see this again, I'll investigate further.
