### ISSUE TITLE
HC-App, Enhancement: Adjust "Hash Cash" view for long names and last list item

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#222]
These issues likely exist in other views, but I'll focus on the "Hash Cash" view from within a specific run admin panel.
* Long hasher names run off the end of the screen
* The last hasher on the list has their info partially covered by the "hamburger" menu button

![Screenshot_20220104-092327](https://user-images.githubusercontent.com/49632769/148098917-11fdc202-8dab-4d1d-81d1-dd1dcc50edbf.png)

**Comment by James-A-White** [comment]
Fixed in 1.0.70
