### ISSUE TITLE
Button "Email run counts"

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#23]
Not sure what this one does.  If it's supposed to send a mail to the hasher it doesn't work for me.  If it sends a demand to the admin then some admins might have spam

Sugar Tits

(on Iphone SE)

**Comment by James-A-White** [comment]
Have you checked your spam folder? I'll re-test and see if something has changed that would prevent this from working. By the way, it sends the e-mail to the account you used to register for the app.

**Comment by James-A-White** [comment]
This should be working now. It’s been tested by several Hashers. Please test again and reopen if necessary
