### ISSUE TITLE
Enchancement, HC-Web (new): Add crosshairs or pin to trail edit menu

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#232]
Editing a trail's start location in the "new" admin portal does not have a crosshair or pin on the map, so there's no visual indicator on the map to show the user where the location is being set. 

![image](https://user-images.githubusercontent.com/49632769/148811204-411edddf-4073-4da1-a3a7-f5f8a3ef6afe.png)

**Comment by James-A-White** [comment]
This is quite odd...  there should be crosshairs (see image below taken from my computer). Which browser and version are you using?

![image](https://user-images.githubusercontent.com/5836474/149512262-904c0298-f125-49c1-b3e9-95ba5c50c1c0.png)

**Comment by diabWH3** [comment]
Was using latest version of Chrome, but did some more testing and realized I needed to force a cache refresh (Ctrl + F5). It works now. Issue can be closed!
