### ISSUE TITLE
BUG, FB Integration: SeaMon H3 events not auto-pulling from Facebook

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#233]
There is a trail for SeaMon H3 tonight (Monday, 1/10/2022) and the Facebook event for it got posted well over 12 hours ago, but HC has not auto-populated the event. Would this have something to do with the two Test events that were created to troubleshoot Issue #170 last week?

I will manually create today's run in HC, but would love to have FB integration operational again.

**Comment by James-A-White** [comment]
Ohhh... that's not good. I'll have to investigate after work today. You're not on our "naughty list" of Kennels that should be pulling from FB but the integration is not working (although South Sound is on the naughty list).  I'll take a look and see what's going on.

**Comment by James-A-White** [comment]
Just sent an e-mail on this. This is a result of me loading DIAB's user profile in my phone to troubleshoot another issue. This caused my Facebook token to get pushed into his personal Hasher record and that of the SeaMon Kennel. If you re-authenticate with Facebook using the "login with 3rd party" button in the profile menu, it should resolve the issue.

I'm going to leave this open until we have confirmed that it is working.

By the way, we poll Facebook for runs up to four days after the run event, so if you log in now, you can expect to see the run appear in the past runs list. If you wait a few more days, I'll have to change some settings to bring in the old run to confirm that it's working.

**Comment by diabWH3** [comment]
@James-A-White , good note about pinging Facebook after-the-fact. I just checked and the app seems to have successfully merged my manually-created event with the Facebook event details, which is fantastic! It doesn't appear we lost any attendance or Hash Cash data either. That's super awesome!

![Screenshot_20220112-151527](https://user-images.githubusercontent.com/49632769/149238182-40132f31-b06a-4068-acf8-3577932158d4.png)

![Screenshot_20220112-151503](https://user-images.githubusercontent.com/49632769/149238184-c2305c1d-9554-49c4-bd71-9c5a8ed5a7e4.png)

**Comment by James-A-White** [comment]
Cool... will close this one. Glad the system is working as designed!
