### ISSUE TITLE
Bug, HC-App: Tacoma H3 Mismanagement (Shackless!!!) cannot edit run # from app

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#245]
Screenshot taken by hasher "Shackless!!!" while trying to edit the Run # for Tacoma H3 #783 on 1/29/2022. HC tracks this trail as #1 as it's the first run in the app, but certainly not the kennel's first run. The user, a member of mismanagement, changes the number in the app and clicks the "Save" button, but only receives the endless spinning wheel of death. I've directed him to the web portal for now; awaiting feedback whether or not he can access that and make the necessary change. Please note: he's able to successfully change info in the "Details" view, so it may be just the "Other" view that is causing issues.

![2022-01-18 08_49_04-(no subject) - downwitda@gmail com - Gmail](https://user-images.githubusercontent.com/49632769/149981660-35acdafd-19c1-4832-9248-07215206cf92.jpg)

**Comment by James-A-White** [comment]
Fixed in 1.0.74. Regression caused when I fixed a decimal point as comma bug a few weeks back.
