### ISSUE TITLE
Run list -> Add new run window on narrower browser window

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#27]
If you narrow your window the pop up "New Run" window is not resized and controls like close are not visible.
This is the same for email templates etc...

**Comment by James-A-White** [comment]
I'll see what I can do to address this, although the HcWeb application is not intended to be used from narrow screens.  Can you tell me how you are using the HcWeb app that would result in a narrow browser window (e.g. phone or tablet, etc?).

**Comment by modderkabouter** [comment]
Just on a macbook pro, using Opera.

It happens when I make the window smaller (so no auto adjusting but just falling off the window)

**Comment by James-A-White** [comment]
We are moving away from having end users access the portal. So going to close this issue.
