### ISSUE TITLE
BUG: Facebook feed, overlapping keywords

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#284]
The Seattle, Washington area has one Facebook group that represents multiple kennels. With no surprise, we have some overlap in our kennel acronyms, which is causing duplicate events in HC-App: Puget Sound H3 (PSH3) events are also populating under the Seattle H3 (SH3) kennel.

![Screenshot_20220303-180318](https://user-images.githubusercontent.com/49632769/156685230-c152addb-ec03-4150-adf2-d3ab4b7f4d4a.png)

**Comment by James-A-White** [comment]
OK, we've fixed this in the backend. It's quite easy to fix, we added to the Facebook tags "-SH3" to the PSH3 site and "-PSH3" to the SH3 site. I think this will fix it, but there's a possibility that this might prevent the PSH3 runs from coming in (I can't remember the exact logic I implemented). If that's the case, just let me know and we'll take "-SH3" off of the PSH3 Kennel.  I'll leave this open for now until we confirm it's working.

**Comment by diabWH3** [comment]
Thanks! It's not too often that PSH3 will create a Facebook event (mostly
old retirees these days), but I'll check the functionality next time we do
and will report back if something is broken still.

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
