### ISSUE TITLE
RSVP

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#30]
When tapping "Going" it takes some milliseconds to change to the "V", if you don't have enough patience and tap twice, you're being shown as going twice.

**Comment by James-A-White** [comment]
Good catch. I need to disable the gesture detection while the transaction is in process. Can you tell me where you pressed? There are several places where you can RSVP (directly from the main runs view and also in the run details view under the RSVP tab).

**Comment by modderkabouter** [comment]
run details, RSVP

**Comment by James-A-White** [comment]
Confirmed fix d in 0.9.200.
