### ISSUE TITLE
Member issue

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#31]
At Manage members -> green arrow down I have got 10 followers but can only see 3 (myself included), so not sure about the 10 there...

Also, about membership, for example at bmph3 it's lifetime membership, is that selectable somewhere?

I only can put 'add 1 month' or 'add 6 months'

**Comment by James-A-White** [comment]
This should be resolved now. I've added a "permanent membership" option and you should see all followers. Please give it another try.  I'm going to close this, but feel free to re-open it if the problem persists.
