### ISSUE TITLE
stateful link to portal page for a hash

### ISSUE THREAD

**Issue by mcr** [James-A-White/HarrierCentral#313]
I login to portal.harriercentral.com, and I get a list of hashes I manage.
I select one, and I get to:
https://portal.harriercentral.com/#kennelHashersPage
but that doesn't have the hash name/number/whatever in it.  So I can't book mark it, and I can't share the link to less clueful mis-management.

**Comment by James-A-White** [comment]
Thanks for the user input. This has been fixed. If you click on the Copy HC Web Link button, it will copy a stateful link to the run that you can share by email.  Let me know if this is not what you were looking for by re-opening this GitHub issue.

OnOn!

Open

![IMG_44C37422F49B-1](https://user-images.githubusercontent.com/5836474/179177106-ce61d487-5042-4615-8405-12d7f605371c.jpeg)
Y
