### ISSUE TITLE
Run Locationss

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#32]
When clicking on the kennel, and clicking on View run locations, you see "Run Locationss"

**Comment by modderkabouter** [comment]
Also, at the Run Locationss the map is not centered on the kennel runs, but somewhere on the other side of the world (changed it to Brussels earlier on, so might have had something to do with that)

**Comment by James-A-White** [comment]
Can you test this again and walk me through the specific Kennels you are clicking on?

**Comment by modderkabouter** [comment]
ok will do

**Comment by James-A-White** [comment]
Confirmed fixed in 0.9.200.
