### ISSUE TITLE
HC-App: Add "x" button to search bar in "Upcoming Runs" view

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#322]
Add an "X" button to quickly empty search criteria on the "Upcoming Runs" view.

![Screenshot_20220627-141028](https://user-images.githubusercontent.com/49632769/176036322-f185a9cb-c710-42e7-9c1f-b465b72f9551.png)

**Comment by James-A-White** [comment]
Fixed in 1.1.1

Actually, the 'X' was there, but because of a behavior change in Flutter, it was now colored white. I've explicitly set it to dark grey. This affected other search bars as well and has been fixed in all.
