### ISSUE TITLE
HC-App: "Explore Runs" view does not show markers until search parameter is entered

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#323]
When viewing the "Explore Runs" screen, I cannot see any trail markers until I start typing something in the search bar. "Show/hide kennels" is the only option that seems to work without an entry in the search bar.

![Screenshot_20220627-141216](https://user-images.githubusercontent.com/49632769/176036669-6da749ce-3195-4d5c-8a08-168e609d501f.png)

![Uploading Screenshot_20220627-141235.png…]()

**Comment by James-A-White** [comment]
Ahhh... good catch!  This will be an urgent fix. Should roll out a patch tomorrow.

**Comment by James-A-White** [comment]
Fixed in 1.1.1

This was a regression regression related to a change in the run query architecture that enables the future runs page to display text dividers.
