### ISSUE TITLE
HC-App: "Run Counts" list - Cannot navigate to trail details

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#324]
When viewing my past runs for a kennel, clicking the run does not take me to the event details page. If that's intentional, would it be possible to add that as an enhancement? I can't remember if older versions of the app did that or not.

![Uploading Screenshot_20220627-141540.png…]()

**Comment by James-A-White** [comment]
Confirmed on my phone as well. Will also fix tomorrow.

Many thanks for the testing!

**Comment by James-A-White** [comment]
Fixed in 1.1.1

This was a regression regression related to a change in the run query architecture that enables the future runs page to display text dividers.
