### ISSUE TITLE
HC-App: Buttons on receipts page are all wonky

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#325]
Weird looking "Save Receipt" button.

![Screenshot (Jun 28, 2022 8 38 51 PM)](https://user-images.githubusercontent.com/49632769/176348270-1a59060d-d312-450e-a4fc-5c1e2a7cdbad.jpg)

**Comment by James-A-White** [comment]
Confirmed in 1.1.1.   Will fix in next release.

**Comment by James-A-White** [comment]
Fixed. Will be included in next release.
