### ISSUE TITLE
[HC-App] Some external link buttons use the app's internal browser

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#332]
When using the "Pay with PayPal" or "Visit Event on Facebook" buttons (and maybe others?), the destinations open inside a browser window tied to the app, which does not preserve any login cookies the user may already have installed, so forces the user to log into Facebook or PayPal manually each time. Luckily, the trail map link works fine and opens in the mobile device's default maps app (Google Maps for me on Android). This internal browser behavior also makes it hard to complete a PayPal payment and return back to the trail payment screen to confirm successful payment. One typically has to force close the app and restart it.

**Comment by James-A-White** [comment]
Fixed in 1.5.0.
