### ISSUE TITLE
HC-App, Enhancement: Allow user to determine their display name 

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#333]
Add a function in the user profile screen to choose which name to display on all other pages: hash name or real name. Unnamed hashers (i.e. Just Jack) who eventually earn a hash name cannot choose to then display as their hash name.

Below is a screenshot where a hasher, formerly named "Just Jack", had to delete his real name and replace it with a hacky work-around in order for the app to display his hasher name, despite having filled that out in his profile.

Related to #272, #267, and #125 .

![Screenshot_20221108-081607](https://user-images.githubusercontent.com/49632769/200618287-e71a2e38-b281-4bfb-976f-a8e43ecee6bc.png)

**Comment by James-A-White** [comment]
Fixed in 1.5.0.  

![image](https://user-images.githubusercontent.com/5836474/222710529-fc8dd5d7-1c31-4374-a877-62be3bd3cbf9.png)
