### ISSUE TITLE
App -> Manage members menu

### ISSUE THREAD

**Issue by modderkabouter** [James-A-White/HarrierCentral#35]
In the Manage members the small red pop up menu (add new hasher, find hasher, sort by date etc..) is not in an ideal place, definitely when you want to access the last hasher in the list.  It's right on top of the email/... buttons.

Maybe better in the title bar?

**Comment by James-A-White** [comment]
I can take a look at this. Thx for the feedback. I think it can be resolved in this version.

**Comment by James-A-White** [comment]
Added some space at the bottom of the list. Closed in 0.9.210+450.
