### ISSUE TITLE
Email Run Details errors when trying to send

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#43]
In the app, within the admin view on a specific event (SeaMon H3 #307 on August 16, 2021), using the "Email Run Details" button. Both the "Quick Send Email" and "Send Email" buttons produce the following error with the default email template:

"Error sending emails
There was a problem sending run detail e-mails to hashers.
Please try again later or contact us at connect@harriercentral.com"

**Comment by James-A-White** [comment]
This should be resolved. I'm going to close it, but if you have any additional issues, please reopen or create a new issue record.
