### ISSUE TITLE
App: New users trying to register via Facebook OAuth get perpetual "spinning wheel" or other error

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#45]
New users trying to create profiles via the app & FB authentication get a perpetual "spinning wheel" or have also seen an error:
"URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app's Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs."

**Comment by James-A-White** [comment]
Fixed in 0.9.200. Closing. Please reopen if it still does not work for you.
