### ISSUE TITLE
App: New user manual registration leads to app hangup / no ability to progress

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#46]
New users creating an account manually inside the app have this response:
"the "create new Account" gives you boxes to fill but once you click "create account" the button just goes away and you are left with the boxes to fill out"

Force-quitting the app and restarting it seems to get these users logged in with their profile working normally.

**Comment by James-A-White** [comment]
Can you clarify a bit... are you trying to create a new user from your existing app logged in as you, or is this a fresh install of the app that's not working properly?  Can you see if you can repeat this using the current version (0.9.200)? Thanks!

**Comment by James-A-White** [comment]
Doh!  Stupid programmer error  🤦         

Fixed on the server side. Please confirm on your end when you have the chance.

Thx!

**Comment by diabWH3** [comment]
Sounds like you figured it out, but it was reported from new users self-registering on their mobile devices. Will reopen ticket if I get any more reports from the kennel.
