### ISSUE TITLE
BUG: Old account cannot be accessed on new app install

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#56]
A user with an account dating back to Feb. 2020, Tastes Like Jesus, is finally re-installing the app to help us test it with SeaMon H3. He has uninstalled the old version and installed the recent (as of today, 8/16/2021) Android release, but cannot log into his account. 

He receives an "invite code not found in the system" error and never gets a chance to enter his personal invite code.

Awaiting a screenshot from the user; will add that to the issue when he sends it.

**Comment by James-A-White** [comment]
I looked in the database and he's still there. Looks like something was changed on his account on Aug 3rd this year. His invite code is ESPTGY. Can you try that and let me know if it works? Thx!

**Comment by diabWH3** [comment]
August 3rd may have been when he came back to the app and re-tried logging in after our initial testing in early 2020. I'm not sure what he would have changed, though. When I saw him last night, his app never fully passes the logo/entry graphic and errors before ever allowing him to enter an invite code. He has tried uninstalling and reinstalling the app, with no success or change in behavior.

**Comment by diabWH3** [comment]
Screenshot from user:

![2021-08-16](https://user-images.githubusercontent.com/49632769/129761568-cb6d36cf-f837-4e72-880b-30f6cae9d560.png)

**Comment by diabWH3** [comment]
User cleared phone cache using [these instructions](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android) and loaded the app using his current Invite Code. He now successfully has access to his account! Thanks for the insight on Android app caching.
