### ISSUE TITLE
Kennel search not resetting with canceled ("X") search

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#6]
To reproduce in Kennel/Home screen:

- Begin to type in the search box. Search results will begin to appear.
- Tap the "x" to cancel the search
- List of kennels still shows only search results. If you use the keyboard to "backspace" the search results, it clears the search filters appropriately.

**Comment by James-A-White** [comment]
Oops... forgot to invoke the refresh method on the onTap event. Fixed in 0.8.130.

Thanks for the feedback DIAB.
