### ISSUE TITLE
Spinning Wheel of Death on "Add Virgin/Visitor" on trail admin page

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#7]
Attempting to manually add a virgin/visitor via the "Manual check in" page and get a "spinning wheel" loading screen that eventually times out without adding the attendee info. This happens for both virgin and visitor options, even when filling out all fields (name, email, phone).

Android OS, v0.8.129

**Comment by diabWH3** [comment]
This bug comes from using the "hamburger" button on the bottom right. If I use the search box returning empty results and then click "Can't find a Hasher? Click here to add...", that functionality works as expected.

**Comment by James-A-White** [comment]
Closed in 0.8.140. Significant updates to the "Find Hasher" page. Needs testing

**Comment by diabWH3** [comment]
So far, so good. Both search fields are easy to use and adding new hasher
entries is a breeze and seems to work great, including custom profile
photos/images!

On-On,

*Dick in a Box*
*Visit our website at www.wh3.org <http://www.wh3.org> or our Facebook
Group <https://www.facebook.com/groups/WaHHH/>*
