### ISSUE TITLE
BUG, HC-Web: Duplicate admin accounts > kennel control did not transfer to new account

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#77]
Putting this as its own issue for better tracking/resolution.

I started working with HC-Web under a hash-related email address (diab@wh3.org) and was granted "Super Owner" access to the SeaMon H3 kennel. Once Facebook event integration was ready to test, I used my FB-auth address (downwitda@gmail.com) to use for that kennel's events. 

Opee attempted to transfer ownership of the kennel from the wh3.org to the gmail.com address, but it still appears that not all functions transferred properly. My HC-Web login for the wh3.org account has been removed, but I cannot manage the kennel or its members under the newer gmail.com account.

Until this is resolved, I can't adjust any high-level settings for the kennel.

**Comment by James-A-White** [comment]
I've looked at that account and it appears to have all required permissions. Can you tell me more specifically what you are not able to access? Thx!

**Comment by diabWH3** [comment]
The "Kennels" and "Runs" views are blank. The "Hashers" tab shows members of SeaMon H3, but I cannot edit any of their info (including an incorrect email address for hasher "Needs a Dick").

![2021-08-30 09_09_58-Calendar - josh johnson@encoreglobal com - Outlook](https://user-images.githubusercontent.com/49632769/131370073-97ecc7fd-c7e2-4284-8423-e388c452b50d.jpg)

![2021-08-30 09_09_27-Calendar - josh johnson@encoreglobal com - Outlook](https://user-images.githubusercontent.com/49632769/131370075-22bcdc32-f95c-4b64-9a72-010620c40867.jpg)

![2021-08-30 09_09_13-Calendar - josh johnson@encoreglobal com - Outlook](https://user-images.githubusercontent.com/49632769/131370076-8dda052a-7102-402c-83f4-fd195187ed7d.jpg)

**Comment by diabWH3** [comment]
Also blank: the "Run Attendance", "P&L Report", and "Hash Cash Report" views.
I have one saved Email Template, but haven't yet seen it work (but our run details have been released within 24 hours of trail start time the past couple weeks, so that's probably the reason it hasn't run yet).

**Comment by diabWH3** [comment]
I realized I could edit some user info; I think they have to have SeaMon H3 set to their Home Kennel before I can edit their member info. Is there a way to add new members via the HC-Web interface, or does that all have to be done in the app?

**Comment by James-A-White** [comment]
I believe this is fixed now. Can you please test? If you see any strange behavior please feel free to reopen this or create a new issue. My apologies that it took me a while to get to this. Thanks! Op
