### ISSUE TITLE
Error picking image when creating virgin/visitor

### ISSUE THREAD

**Issue by diabWH3** [James-A-White/HarrierCentral#8]
Android OS, v 0.8.129

To recreate:
- Go to manual hasher check-in for a trail
- Search for new hasher
- Click "Can't find a Hasher? Click here to add..." button
- Scroll down, click "Update Profile Image"
- Both "Camera" and "Gallery" options, once a photo has been selected, result in a "Error picking image" message
- The "Avatar" selection works fine and "FB Photo" is still TBD

**Comment by James-A-White** [comment]
I was not able to recreate this bug on my Android or iOS phone using v 0.8.130. I was able to successfully add hashers on both platforms.  I tried to disallow permissions for the camera and the app successfully prompted me for camera access.  On one occasion, the app rebooted itself after taking the picture - I'm wondering if it could be related to uploading photos when the network connection is marginal.

Could you try again and see if you can collect more info on what might be causing this?

Thanks!

Opee

**Comment by diabWH3** [comment]
Now testing on v 0.8.130 and adding a hasher through this method seems to submit fine. However, after submitting a new hasher (complete with first/last names, email address, and custom profile photo), I cannot find that person in the search field in order to add them to the kennel or check them in for the trail. 

Also, using the "hamburger" menu to add a new hasher does not work at all. When a name is entered that does not exist in the database, it just shows the spinning wheel of death; no option to add a new hasher or anything like that.

**Comment by James-A-White** [comment]
Please test again under 0.8.140. I think both issues have been fixed.
