### ISSUE TITLE
Allow a Hasher's profile to have two emails. One for integration with FB (and potentially others) and one for everything else

### ISSUE THREAD

**Issue by James-A-White** [James-A-White/HarrierCentral#81]
Allow a Hasher's profile to have two emails. One for integration with FB (and potentially others) and one for everything else

**Comment by James-A-White** [comment]
Completed several versions ago.

**Comment by diabWH3** [comment]
This is a great feature for people who split their email and social media
across different accounts!
However, this is an error message I got when trying to update my profile
address to my "hash" account ***@***.***) and link my "personal" account
to Facebook ***@***.***).
I'm guessing it's a result of my account history, where I started beta
testing with my "hash" account and then moved to my "personal" account when
it became necessary to connect my kennel's Facebook page to Harrier Central.

[image: Screenshot_20211202-113110.png]
